// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, content, user_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $4
) RETURNING id, content, user_id, created_at, updated_at
`

type CreateNoteParams struct {
	ID        uuid.UUID
	Content   string
	UserID    uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.Content,
		arg.UserID,
		arg.CreatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes 
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNotesByID = `-- name: GetNotesByID :many
SELECT id, content, user_id, created_at, updated_at FROM notes
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetNotesByID(ctx context.Context, userID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteByID = `-- name: UpdateNoteByID :exec
UPDATE notes
SET content = $2, updated_at = $3
WHERE id = $1
`

type UpdateNoteByIDParams struct {
	ID        uuid.UUID
	Content   string
	UpdatedAt time.Time
}

func (q *Queries) UpdateNoteByID(ctx context.Context, arg UpdateNoteByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateNoteByID, arg.ID, arg.Content, arg.UpdatedAt)
	return err
}
