// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createResetPasswordToken = `-- name: CreateResetPasswordToken :one
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, user_id, token_hash, expires_at, used_at
`

type CreateResetPasswordTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateResetPasswordToken(ctx context.Context, arg CreateResetPasswordTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createResetPasswordToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getResetPasswordToken = `-- name: GetResetPasswordToken :one
SELECT id, user_id, token_hash, expires_at, used_at FROM password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) GetResetPasswordToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getResetPasswordToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :exec
UPDATE password_reset_tokens
SET used_at = $1
WHERE token_hash = $2
`

type MarkTokenAsUsedParams struct {
	UsedAt    sql.NullTime
	TokenHash string
}

func (q *Queries) MarkTokenAsUsed(ctx context.Context, arg MarkTokenAsUsedParams) error {
	_, err := q.db.ExecContext(ctx, markTokenAsUsed, arg.UsedAt, arg.TokenHash)
	return err
}
